from batou.debug.settings import DebugSettings
from mock.mock import Mock
from pathlib._local import PosixPath
from typing import (
    Dict,
    List,
    Optional,
    Union,
)


class FileDescriptorTracker:
    def __init__(self, environment_name: str, debug_settings: DebugSettings): ...
    def _install_local_hook(self): ...
    def _track_close(self, fd: int): ...
    def _track_open(self, fd: int, path: Union[PosixPath, str], mode: str = ...): ...
    @classmethod
    def cleanup(cls): ...
    def generate_reports(self, hosts: List[Mock]): ...
    def get_remote_logs(self, gateway: Mock) -> Dict[str, int]: ...
    def install_remote_hook(self, gateway: Mock): ...
    def report(self, location: str = ..., env_name: Optional[str] = ...): ...
