from batou.debug.settings import DebugSettings
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Tuple,
)

class FileDescriptorTracker:
    enabled: bool
    verbose: bool
    debug_settings: DebugSettings
    environment_name: str
    fd_records: Dict[str, Dict[str, Any]]
    original_open: Any
    total_opens: int
    total_closes: int
    remote_opens: Dict[str, int]
    _open_fds: Dict[int, Tuple[str, str, str]]
    _fd_tracking_logs: List[Tuple[str, int, str, str, str]]
    _instance: Optional["FileDescriptorTracker"]

    def __init__(self, environment_name: str, debug_settings: DebugSettings): ...
    def _install_local_hook(self): ...
    def _track_close(self, fd: int): ...
    def _track_open(self, fd: int, path: str, mode: str = ...): ...
    @classmethod
    def cleanup(cls): ...
    def generate_reports(self, hosts: List[Any]): ...
    def get_fd_tracking_stats(self) -> Dict[str, Any]: ...
    def get_remote_logs(self, gateway: Any) -> Optional[Dict[str, int]]: ...
    def install_remote_hook(self, gateway: Any): ...
    def report(self, location: str = ..., env_name: Optional[str] = ...): ...
    def show_summary(self): ...
