from pathlib import Path
from posix import DirEntry

from batou.remote_core import FDTrackingStats

def _track_fd_close(fd: int) -> None: ...
def _track_fd_open(fd: int, path: DirEntry | str | Path, mode: str = ...) -> None: ...
def get_remote_fd_tracking_stats() -> FDTrackingStats: ...
def init_remote_fd_tracking(track_fds_level: int) -> None: ...
def install_remote_fd_tracking_hook() -> None: ...
