from pathlib import Path
from posix import DirEntry
from typing import (
    Dict,
    Union,
)

def _track_fd_close(fd: int): ...
def _track_fd_open(fd: int, path: Union[DirEntry, str, Path], mode: str = ...): ...
def get_remote_fd_tracking_stats() -> Dict[str, Union[int, bool]]: ...
def init_remote_fd_tracking(track_fds_level: int): ...
def install_remote_fd_tracking_hook(): ...
