from pathlib import Path
from posix import DirEntry

def _track_fd_close(fd: int) -> None: ...
def _track_fd_open(fd: int, path: DirEntry | str | Path, mode: str = ...) -> None: ...
def get_remote_fd_tracking_stats() -> dict[
    str,
    int
    | bool
    | list[tuple[int, str, str, str]]
    | list[tuple[str, int, str, str, str]]
    | dict,
]: ...
def init_remote_fd_tracking(track_fds_level: int) -> None: ...
def install_remote_fd_tracking_hook() -> None: ...
