from batou.component import Component
from typing import Dict

class TemplateStats:
    def __init__(self): ...
    def collect_component_stats(self, components: list[Component]): ...
    def get_stats(self) -> Dict[str, int]: ...
    def humanize(self) -> str: ...
    def record_hit(self, count: int = ...): ...
    def record_miss(self, count: int = ...): ...
    def reset(self): ...
    def update_size(self, size: int): ...
