class AppEnv:
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...

class CleanupUnused:
    def update(self): ...
    def verify(self): ...

class LockedRequirements:
    def update(self): ...
    def verify(self): ...

class VirtualEnv:
    def update(self): ...
    def verify(self): ...
