from typing import (
    Any,
    List,
)
from collections.abc import Iterator

class DMGExtractor:
    def __enter__(self): ...
    def __exit__(self, type: None, value: None, tb: None): ...
    def get_names_from_archive(self) -> Iterator[Any]: ...
    def update(self): ...

class DMGVolume:
    def __init__(self, path: str): ...
    def _mount(self) -> str: ...
    def _unmount(self): ...
    def copy_to(self, target_dir: str): ...
    def namelist(self): ...

class Extract:
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...

class Extractor:
    @classmethod
    def can_handle(cls, archive: str) -> bool: ...
    def configure(self): ...
    @classmethod
    def extract_base_name(cls, archive: str) -> str: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def verify(self): ...

class Untar:
    def configure(self): ...
    def get_names_from_archive(self) -> list[str]: ...
    def update(self): ...

class Unzip:
    def get_names_from_archive(self) -> list[str]: ...
    def update(self): ...
