import types
from collections.abc import Iterator
from typing import Any, Self

class DMGExtractor:
    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        tb: types.TracebackType | None,
    ) -> bool | None: ...
    def get_names_from_archive(self) -> Iterator[Any]: ...
    def update(self) -> None: ...

class DMGVolume:
    def __init__(self, path: str) -> None: ...
    def _mount(self) -> str: ...
    def _unmount(self) -> None: ...
    def copy_to(self, target_dir: str) -> None: ...
    def namelist(self) -> list[Any]: ...

class Extract:
    def configure(self) -> None: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...

class Extractor:
    @classmethod
    def can_handle(cls, archive: str) -> bool: ...
    def configure(self) -> None: ...
    @classmethod
    def extract_base_name(cls, archive: str) -> str: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def verify(self) -> None: ...

class Untar:
    def configure(self) -> None: ...
    def get_names_from_archive(self) -> list[str]: ...
    def update(self) -> None: ...

class Unzip:
    def get_names_from_archive(self) -> list[str]: ...
    def update(self) -> None: ...
