class Build:
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...


class Configure:
    def configure(self): ...
    def update(self): ...
    def verify(self): ...


class Make:
    def update(self): ...
    def verify(self): ...
