class Download:
    def _update_requests(self): ...
    def _update_urllib(self): ...
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def update(self): ...
    def verify(self): ...
