from typing import (
    Any,
    List,
    Tuple,
)
from collections.abc import Iterator


def convert_mode(string: str) -> int: ...


def ensure_path_nonexistent(path: str) -> None: ...


def limited_buffer(
    iterator: Iterator[Any],
    limit: int,
    lead: int,
    separator: str = ...,
    logdir: str = ...
) -> tuple[list[str], bool, str]: ...


class Content:
    def render(self): ...


class Directory:
    def configure(self): ...
    def last_updated(self, key: str = ...) -> float: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def update(self): ...
    def verify(self): ...


class File:
    def configure(self): ...
    def last_updated(self, key: str = ...) -> float: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...


class FileComponent:
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...


class Group:
    def update(self): ...
    def verify(self): ...


class JSONContent:
    def render(self): ...


class ManagedContentBase:
    def _render(self): ...
    def configure(self): ...
    def update(self): ...
    def verify(self, predicting: bool = ...): ...


class Mode:
    def _select_stat_implementation(self): ...
    def configure(self): ...
    def update(self): ...
    def verify(self): ...


class Owner:
    def update(self): ...
    def verify(self): ...


class Presence:
    def configure(self): ...
    def last_updated(self, key: str = ...) -> float: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def update(self): ...
    def verify(self): ...


class Purge:
    def configure(self): ...
    def update(self): ...
    def verify(self): ...


class Symlink:
    def configure(self): ...
    def update(self): ...
    def verify(self): ...


class SyncDirectory:
    def configure(self): ...
    @property
    def exclude_arg(self) -> str: ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def update(self): ...
    def verify(self): ...


class YAMLContent:
    def render(self): ...
