from typing import (
    Any,
)

def ensure_empty_directory(path: str): ...
def exactly_one(*args) -> bool: ...

class Clone:
    def configure(self): ...
    def current_branch(self) -> str: ...
    def current_revision(self) -> str: ...
    def current_tag(self) -> str: ...
    def has_changes(self) -> bool: ...
    def has_incoming_changesets(self) -> str: ...
    def has_outgoing_changesets(self) -> bool: ...
    def remote_url(self) -> str: ...
    def untracked_files(self) -> list[Any | str]: ...
    def update(self): ...
    def verify(self): ...
