from typing import (
    Any,
)

class Clone:
    def configure(self): ...
    def current_branch(self) -> str: ...
    def current_revision(self, long: bool = ...) -> str: ...
    def has_changes(self) -> bool: ...
    def has_incoming_changesets(self): ...
    def has_outgoing_changesets(self): ...
    @property
    def revision_or_branch(self) -> str: ...
    def untracked_files(self) -> list[Any | str]: ...
    def update(self): ...
    def verify(self): ...
