def ServiceCheck(description: str, **kw) -> NRPEService: ...

class NRPEService:
    @property
    def check_command(self) -> str: ...
    def configure(self): ...
    @property
    def nrpe_command(self) -> str: ...

class NagiosServer:
    def configure(self): ...

class Service:
    @property
    def check_command(self) -> str: ...
    def configure(self): ...
