from typing import Any

# Note: ServiceCheck follows batou naming convention (not PEP8)
def ServiceCheck(description: str, **kw: Any) -> NRPEService: ...  # noqa: N802

class NRPEService:
    @property
    def check_command(self) -> str: ...
    def configure(self) -> None: ...
    @property
    def nrpe_command(self) -> str: ...

class NagiosServer:
    def configure(self) -> None: ...

class Service:
    @property
    def check_command(self) -> str: ...
    def configure(self) -> None: ...
