from typing import Literal

class Package:
    def configure(self): ...
    @property
    def namevar_for_breadcrumb(self) -> str: ...
    def update(self): ...
    def verify(self): ...

class VirtualEnv:
    def configure(self): ...
    @property
    def python(self) -> str: ...

class VirtualEnvDownload:
    def configure(self): ...

class VirtualEnvPy:
    def update(self): ...

class VirtualEnvPy2_7:  # noqa: N801
    def configure(self) -> None: ...

class VirtualEnvPyBase:
    installer: Literal["pip", "easy_install"]
    def pip_install(self, pkg: Package): ...
    def update(self): ...
    def update_pkg(self, pkg: Package): ...
    def verify(self): ...
    def verify_pkg(self, pkg: Package): ...
