from typing import Any, Literal

class Program:
    deployment: Literal["hot", "cold"]
    def configure(self) -> None: ...
    def ctl(self, args: str, **kw: Any) -> tuple[str, str]: ...
    def evade(self, component: RunningSupervisor) -> None: ...
    def is_running(self) -> bool: ...
    def update(self) -> None: ...
    def verify(self) -> None: ...

class RunningHelper:
    def is_running(self) -> bool: ...

class RunningSupervisor:
    def reload_supervisor(self) -> None: ...
    def update(self) -> None: ...
    def verify(self) -> None: ...

class StoppedSupervisor:
    def verify(self) -> None: ...

class Supervisor:
    deployment_mode: Literal["hot", "cold"]
    loglevel: Literal["info", "debug", "warn", "error", "critical"]
    def configure(self) -> None: ...
