from typing import Tuple

class Program:
    def configure(self): ...
    def ctl(self, args: str, **kw) -> tuple[str, str]: ...
    def evade(self, component: RunningSupervisor): ...
    def is_running(self) -> bool: ...
    def update(self): ...
    def verify(self): ...

class RunningHelper:
    def is_running(self): ...

class RunningSupervisor:
    def reload_supervisor(self): ...
    def update(self): ...
    def verify(self): ...

class StoppedSupervisor:
    def verify(self): ...

class Supervisor:
    def configure(self): ...
