import os
import re
import tempfile
import time

import mock
import pytest

from batou.debug.fd_tracker import FileDescriptorTracker
from batou.debug.settings import DebugSettings


@pytest.fixture(scope="module", autouse=True)
def reset_fd_tracking_hook_module():
    """Reset FD tracking hook at start of test module and restore at end.

    This is critical: FD tracking hook wraps all file opens globally
    and close_hook can interfere with garbage collection in other tests.

    Module-scoped ensures this runs before any other fixtures that might
    initialize FD tracking (like sample_service loading .batou.json).
    """
    import builtins as _builtins

    # Store original open at module start
    original_open_at_module_start = _builtins.open

    # Force reset hook at module start (in case from previous runs)
    FileDescriptorTracker.cleanup()

    yield

    # Cleanup singleton and restore original open at module end
    FileDescriptorTracker.cleanup()
    _builtins.open = original_open_at_module_start


def _cleanup_report_file(env_name, output_dir):
    """Helper to cleanup report files generated by tests."""
    pid = os.getpid()
    deployment_name = os.path.basename(os.getcwd())
    output_file = os.path.join(
        output_dir,
        f"batou_fd_track_{env_name}_{deployment_name}_{pid}.txt",
    )
    if os.path.exists(output_file):
        os.unlink(output_file)


def test_fd_tracker_stack_trace_serialization(monkeypatch, tmpdir):
    """Test that stack traces are stored as serializable tuples."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create a test file - this should track stack traces
    test_file = os.path.join(tmpdir, "test.txt")
    with open(test_file, "w") as f:
        f.write("test")

    # Clean up
    os.unlink(test_file)

    # Check that stack traces are lists of tuples (not FrameSummary objects)
    assert len(tracker.fd_records) > 0
    for path, record in tracker.fd_records.items():
        if record["stack_traces"]:
            for stack in record["stack_traces"]:
                # Each stack should be a list of tuples
                assert isinstance(stack, list)
                if stack:
                    # Each frame should be a tuple (filename, lineno, name)
                    assert isinstance(stack[0], tuple)
                    assert len(stack[0]) == 3
                    filename, lineno, name = stack[0]
                    assert isinstance(filename, str)
                    assert isinstance(lineno, int)
                    assert isinstance(name, str)


def test_fd_tracker_remote_stats_serialization(monkeypatch):
    """Test that remote stats with fd_records can be pickled/unpickled."""
    import pickle

    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    # Simulate remote stats with fd_records (as they come from remote)
    remote_stats = {
        "total_opens": 10,
        "total_closes": 5,
        "open_fds": 5,
        "fd_leak": False,
        "fd_records": {
            "/remote/path/file1.txt": {
                "open_count": 5,
                "modes": {"r": 3, "w": 2},
                "stack_traces": [
                    [
                        ("/path/to/remote/code.py", 42, "function_name"),
                        ("/path/to/another/file.py", 100, "caller"),
                    ]
                ],
            }
        },
    }

    # Try to pickle (simulate RPC serialization)
    pickled = pickle.dumps(remote_stats)
    unpickled = pickle.loads(pickled)

    # Verify structure is preserved
    assert unpickled["fd_records"] == remote_stats["fd_records"]
    assert unpickled["total_opens"] == 10


def test_fd_tracker_merge_remote_fd_records(monkeypatch):
    """Test that remote fd_records are properly merged into local tracker."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Simulate remote stats with fd_records
    remote_stats = {
        "total_opens": 10,
        "fd_records": {
            "/remote/file1.txt": {
                "open_count": 3,
                "modes": {"r": 2, "w": 1},
                "stack_traces": [
                    [("/remote/code.py", 42, "func1")],
                ],
            },
            "/remote/file2.txt": {
                "open_count": 7,
                "modes": {"r": 5},
                "stack_traces": [],
            },
        },
    }

    # Merge into tracker (simulating deploy.py logic)
    for path, record in remote_stats["fd_records"].items():
        host_path = f"[remote_host] {path}"
        if host_path not in tracker.fd_records:
            tracker.fd_records[host_path] = {
                "open_count": 0,
                "modes": {},
                "stack_traces": [],
            }
        tracker.fd_records[host_path]["open_count"] += record["open_count"]
        for mode, count in record.get("modes", {}).items():  # type: ignore[union-attr]
            if mode not in tracker.fd_records[host_path]["modes"]:
                tracker.fd_records[host_path]["modes"][mode] = 0
            tracker.fd_records[host_path]["modes"][mode] += count
        for stack in record.get("stack_traces", []):  # type: ignore[union-attr]
            tracker.fd_records[host_path]["stack_traces"].append(stack)

    # Verify merge
    assert len(tracker.fd_records) == 2
    assert tracker.fd_records["[remote_host] /remote/file1.txt"]["open_count"] == 3
    assert tracker.fd_records["[remote_host] /remote/file2.txt"]["open_count"] == 7
    assert tracker.fd_records["[remote_host] /remote/file1.txt"]["modes"] == {
        "r": 2,
        "w": 1,
    }
    assert (
        len(tracker.fd_records["[remote_host] /remote/file1.txt"]["stack_traces"]) == 1
    )


def test_fd_tracker_filter_tracking_frames(monkeypatch, tmpdir):
    """Test that tracking frames are filtered from stack traces."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create a test file
    test_file = os.path.join(tmpdir, "test.txt")
    with open(test_file, "w") as f:
        f.write("test")

    # Clean up
    os.unlink(test_file)

    # Check that tracking frames are filtered
    assert len(tracker.fd_records) > 0
    for path, record in tracker.fd_records.items():
        if record["stack_traces"]:
            for stack in record["stack_traces"]:
                # Convert back to tuples for easier checking
                stack_tuples = [(f, lineno, n) for f, lineno, n in stack]
                # No frame should be from batou/utils.py with tracking function names
                for filename, lineno, name in stack_tuples:
                    if "batou/utils.py" in filename:
                        assert name not in ["open_hook", "_track_open"]


def test_fd_tracker_opt_out_by_default(monkeypatch):
    """Test that FD tracking is disabled by default."""
    monkeypatch.delenv("BATOU_TRACK_FDS", raising=False)

    tracker = FileDescriptorTracker("test", DebugSettings())

    assert not tracker.enabled
    assert not tracker.verbose


def test_fd_tracker_opt_in_via_env_var(monkeypatch):
    """Test that FD tracking is enabled when BATOU_TRACK_FDS is set."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    assert tracker.enabled
    assert not tracker.verbose


def test_fd_tracker_verbose_mode(monkeypatch):
    """Test that verbose mode is enabled via BATOU_TRACK_FDS=2."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    tracker = FileDescriptorTracker("test", DebugSettings())

    assert tracker.enabled
    assert tracker.verbose


def test_fd_tracker_zero_overhead_when_disabled(monkeypatch, tmpdir):
    """Test that disabled tracking has zero overhead."""
    monkeypatch.delenv("BATOU_TRACK_FDS", raising=False)

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Install hook should return early without doing anything

    # Create some files to ensure tracking is disabled
    test_file = os.path.join(tmpdir, "test.txt")
    with open(test_file, "w") as f:
        f.write("test")

    # Report should return early without creating files
    tracker.report("local", "test_env")

    # Verify no opens were tracked
    assert tracker.total_opens == 0


def test_fd_tracker_tracks_opens_with_timestamps(monkeypatch, tmpdir):
    """Test that FD tracking records open events with timestamps in logs."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create a file
    test_file = os.path.join(tmpdir, "test.txt")
    with open(test_file, "w") as f:
        f.write("test")

    # Verify timestamps are recorded in logs
    assert len(tracker._fd_tracking_logs) > 0
    timestamp_pattern = re.compile(r"\d{2}:\d{2}:\d{2}\.\d{3}")
    now, count, path, mode, action = tracker._fd_tracking_logs[0]
    assert timestamp_pattern.match(now)

    # Generate report
    tracker.report("local", "test_env")

    # Verify output file was created
    pid = os.getpid()
    deployment_name = os.path.basename(os.getcwd())
    output_file = f"/tmp/batou_fd_track_test_env_{deployment_name}_{pid}.txt"
    assert os.path.exists(output_file)

    with open(output_file, "r") as f:
        content = f.read()
        # Find the bar line for the most opened FD
        lines = content.split("\n")
        for line in lines:
            if "x FD" in line and "|" in line:
                bar_start = line.index("|") + 1
                bar = line[bar_start:].strip()
                # Bar should be at most 50 characters
                assert len(bar) <= 50


def test_fd_tracker_verbose_stack_traces(monkeypatch, tmpdir):
    """Test that verbose mode captures stack traces."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create a file
    temp_file = os.path.join(tmpdir, "test.txt")
    with open(temp_file, "w") as f:
        f.write("test")

    # Generate report
    tracker.report("local", "test_env")

    # Clean up
    os.unlink(temp_file)

    # Verify output file contains stack traces
    pid = os.getpid()
    deployment_name = os.path.basename(os.getcwd())
    output_file = f"/tmp/batou_fd_track_test_env_{deployment_name}_{pid}.txt"
    assert os.path.exists(output_file)

    with open(output_file, "r") as f:
        content = f.read()
        assert "Stack Traces (grouped by trace):" in content


def test_fd_tracker_performance_overhead_disabled(monkeypatch):
    """Test that disabled tracking has negligible overhead."""
    monkeypatch.delenv("BATOU_TRACK_FDS", raising=False)

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Measure time without tracking
    start = time.time()
    for i in range(100):
        with tempfile.NamedTemporaryFile() as f:
            f.write(b"test")
    _ = time.time() - start  # Verify baseline performance

    # Overhead should be negligible (less than 1% difference in repeated tests)
    # In practice, this test verifies no tracking code path is executed
    assert not tracker.enabled
    assert tracker.total_opens == 0


def test_fd_tracker_performance_overhead_enabled(monkeypatch, tmpdir):
    """Test that enabled tracking has acceptable overhead."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Measure time with tracking
    start = time.time()
    for i in range(100):
        temp_file = os.path.join(tmpdir, f"test_{i}.txt")
        with open(temp_file, "w") as f:
            f.write("test")
        # Clean up
        os.unlink(temp_file)
    _ = time.time() - start  # Verify tracking overhead is acceptable

    # Verify tracking actually happened
    assert tracker.enabled
    assert tracker.total_opens >= 100

    # Clean up
    tracker.report("local", "test_env")


@mock.patch("builtins.open")
def test_fd_tracker_remote_hook_installation(mock_open, monkeypatch):
    """Test that remote hook is installed via execnet gateway."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Mock execnet gateway
    mock_gateway = mock.Mock()
    mock_gateway.remote_exec.return_value.receive.return_value = {
        "fd_records": {},
        "total_opens": 10,
    }

    # Install remote hook
    tracker.install_remote_hook(mock_gateway)

    # Verify remote_exec was called
    assert mock_gateway.remote_exec.called

    # Verify get_remote_logs works
    stats = tracker.get_remote_logs(mock_gateway)
    assert stats is not None
    assert stats["total_opens"] == 10


def test_fd_tracker_remote_hook_not_installed_when_disabled(monkeypatch):
    """Test that remote hook is not installed when tracking is disabled."""
    monkeypatch.delenv("BATOU_TRACK_FDS", raising=False)

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Mock execnet gateway
    mock_gateway = mock.Mock()
    tracker.install_remote_hook(mock_gateway)

    # Verify remote_exec was not called
    assert not mock_gateway.remote_exec.called

    # Verify get_remote_logs returns None
    stats = tracker.get_remote_logs(mock_gateway)
    assert stats is None


def test_fd_tracker_report_ascii_trend_graph(monkeypatch, tmpdir):
    """Test that report generates ASCII trend graph."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create multiple files
    for i in range(5):
        test_file = os.path.join(tmpdir, f"test_{i}.txt")
        with open(test_file, "w") as f:
            f.write("test")

    # Generate report
    tracker.report("local", "test_env")

    # Clean up
    for i in range(5):
        test_file = os.path.join(tmpdir, f"test_{i}.txt")
        os.unlink(test_file)

    # Verify output file was created
    pid = os.getpid()
    deployment_name = os.path.basename(os.getcwd())
    output_file = f"/tmp/batou_fd_track_test_env_{deployment_name}_{pid}.txt"
    assert os.path.exists(output_file)

    # Verify report contains ASCII trend graph
    with open(output_file, "r") as f:
        content = f.read()
        assert "Top 20 Files:" in content
        assert "*" in content  # Bar characters


def test_fd_tracker_grouped_stack_traces(monkeypatch, tmp_path):
    """Test that stack traces are grouped by trace instead of by file."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")

    tracker = FileDescriptorTracker("test", DebugSettings())

    # Create multiple files - they should have same stack trace
    for i in range(3):
        test_file = tmp_path / f"test_{i}.txt"
        with open(test_file, "w") as f:
            f.write("test")

    # Generate report
    tracker.report("local", "test_env")

    # Clean up
    for i in range(3):
        test_file = tmp_path / f"test_{i}.txt"
        os.unlink(test_file)

    # Verify output file was created
    pid = os.getpid()
    deployment_name = os.path.basename(os.getcwd())
    output_file = f"/tmp/batou_fd_track_test_env_{deployment_name}_{pid}.txt"
    assert os.path.exists(output_file)

    # Verify report groups traces together
    with open(output_file, "r") as f:
        content = f.read()
        assert "Stack Traces (grouped by trace):" in content
        # Should show one trace with multiple files, not one trace per file
        assert "Stack Trace #1 (called" in content
        assert "Files with this trace" in content


def test_fd_tracker_generate_reports_with_remote_rpc(monkeypatch):
    """Test that generate_reports calls RPC to get remote FD tracking stats."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Create mock host with RPC (following pattern from test_remote.py)
    host = mock.Mock()
    host.name = "remote-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 15,
        "open_fds": 5,
        "fd_records": {
            "/remote/file1.txt": {
                "open_count": 10,
                "modes": {"r": 8, "w": 2},
                "stack_traces": [],
            }
        },
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify RPC was called
    host.rpc.get_fd_tracking_stats.assert_called_once()

    # Verify remote stats were merged
    assert tracker.remote_opens["remote-host"] == 15
    # total_opens includes remote opens + local file operations for report()
    assert tracker.total_opens >= 15
    assert "[remote-host] /remote/file1.txt" in tracker.fd_records
    assert tracker.fd_records["[remote-host] /remote/file1.txt"]["open_count"] == 10


def test_fd_tracker_generate_reports_when_disabled(monkeypatch):
    """Test that generate_reports returns early when tracking is disabled."""
    monkeypatch.delenv("BATOU_TRACK_FDS", raising=False)

    tracker = FileDescriptorTracker("test-env", DebugSettings())
    assert not tracker.enabled

    # Create mock host with RPC
    host = mock.Mock()
    host.name = "remote-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()

    # Call generate_reports - should return early
    tracker.generate_reports([host])

    # Verify RPC was NOT called (early return at line 390)
    assert not host.rpc.get_fd_tracking_stats.called


def test_fd_tracker_generate_reports_host_without_gateway(monkeypatch):
    """Test that generate_reports skips hosts without gateway."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Create mock host WITHOUT gateway attribute
    host = mock.Mock(spec=["name"])
    host.name = "local-only-host"

    # Call generate_reports - should skip this host (line 394)
    tracker.generate_reports([host])

    # Verify remote stats were not added
    assert "local-only-host" not in tracker.remote_opens


def test_fd_tracker_generate_reports_remote_stats_zero_opens(monkeypatch):
    """Test that generate_reports handles remote stats with 0 opens."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Create mock host with RPC returning 0 opens
    host = mock.Mock()
    host.name = "quiet-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 0,
        "open_fds": 0,
        "fd_records": {},
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify RPC was called but stats were NOT merged (line 396 condition)
    host.rpc.get_fd_tracking_stats.assert_called_once()
    assert "quiet-host" not in tracker.remote_opens


def test_fd_tracker_generate_reports_remote_stats_without_fd_records(
    monkeypatch,
):
    """Test that generate_reports handles remote stats without fd_records."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Create mock host with RPC returning stats but NO fd_records key
    host = mock.Mock()
    host.name = "simple-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 5,
        "open_fds": 0,
        # NO fd_records key (line 405 branch)
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify remote opens were tracked but no fd_records merged
    assert tracker.remote_opens["simple-host"] == 5
    # No fd_records for this host since key wasn't present
    assert not any("simple-host" in path for path in tracker.fd_records.keys())


def test_fd_tracker_generate_reports_verbose_logging(monkeypatch):
    """Test that generate_reports shows verbose logs when enabled."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")  # Verbose mode

    tracker = FileDescriptorTracker("test-env", DebugSettings())
    assert tracker.verbose

    # Create mock host with RPC returning logs
    host = mock.Mock()
    host.name = "verbose-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 20,
        "open_fds": 0,
        "fd_records": {},
        "logs": [
            ("10:15:23.456", 1, "/path/to/file1.txt", "r", "open"),
            ("10:15:24.789", 2, "/path/to/file2.txt", "w", "open"),
        ],
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify RPC was called and stats were tracked
    host.rpc.get_fd_tracking_stats.assert_called_once()
    assert tracker.remote_opens["verbose-host"] == 20


def test_fd_tracker_generate_reports_merges_existing_paths(
    monkeypatch,
):
    """Test that generate_reports handles already existing host paths."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Pre-populate fd_records with existing remote data
    tracker.fd_records["[test-host] /remote/file.txt"] = {
        "open_count": 5,
        "modes": {"r": 5},
        "stack_traces": [],
    }

    # Create mock host with RPC returning same path
    host = mock.Mock()
    host.name = "test-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 3,
        "open_fds": 0,
        "fd_records": {
            "/remote/file.txt": {
                "open_count": 3,
                "modes": {"w": 3},
                "stack_traces": [],
            }
        },
    }

    # Call generate_reports - should merge into existing entry (line 409)
    tracker.generate_reports([host])

    # Verify counts were added, not replaced
    assert tracker.fd_records["[test-host] /remote/file.txt"]["open_count"] == 8
    assert tracker.fd_records["[test-host] /remote/file.txt"]["modes"] == {
        "r": 5,
        "w": 3,
    }


def test_fd_tracker_generate_reports_merges_existing_modes(
    monkeypatch,
):
    """Test that generate_reports handles already existing modes."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "1")

    tracker = FileDescriptorTracker("test-env", DebugSettings())

    # Pre-populate with data that has mode "r"
    tracker.fd_records["[test-host] /remote/file.txt"] = {
        "open_count": 5,
        "modes": {"r": 3},
        "stack_traces": [],
    }

    # Create mock host with RPC returning same mode
    host = mock.Mock()
    host.name = "test-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 2,
        "open_fds": 0,
        "fd_records": {
            "/remote/file.txt": {
                "open_count": 2,
                "modes": {"r": 2},  # Same mode as existing (line 420)
                "stack_traces": [],
            }
        },
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify mode counts were added
    assert tracker.fd_records["[test-host] /remote/file.txt"]["modes"]["r"] == 5


def test_fd_tracker_generate_reports_appends_stack_traces(
    monkeypatch,
):
    """Test that generate_reports appends stack traces from remote."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")  # Verbose mode

    tracker = FileDescriptorTracker("test-env", DebugSettings())
    assert tracker.verbose

    # Create mock host with RPC returning stack traces
    host = mock.Mock()
    host.name = "test-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 5,
        "open_fds": 0,
        "fd_records": {
            "/remote/file.txt": {
                "open_count": 5,
                "modes": {"r": 5},
                "stack_traces": [
                    [
                        ("/remote/code.py", 42, "func1"),
                        ("/another/file.py", 100, "caller"),
                    ]
                ],
            }
        },
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify stack traces were appended (line 425)
    host_path = "[test-host] /remote/file.txt"
    assert len(tracker.fd_records[host_path]["stack_traces"]) == 1
    assert tracker.fd_records[host_path]["stack_traces"][0] == [
        ("/remote/code.py", 42, "func1"),
        ("/another/file.py", 100, "caller"),
    ]


def test_fd_tracker_generate_reports_many_logs(monkeypatch):
    """Test that generate_reports handles more than 10 logs."""
    monkeypatch.setenv("BATOU_TRACK_FDS", "2")  # Verbose mode

    tracker = FileDescriptorTracker("test-env", DebugSettings())
    assert tracker.verbose

    # Create mock host with RPC returning more than 10 logs
    host = mock.Mock()
    host.name = "test-host"
    host.gateway = mock.Mock()
    host.rpc = mock.Mock()
    host.rpc.get_fd_tracking_stats.return_value = {
        "total_opens": 15,
        "open_fds": 0,
        "fd_records": {},
        "logs": [
            (f"10:15:{i:02d}.456", i, f"/path/to/file{i}.txt", "r", "open")
            for i in range(1, 16)
        ],  # 15 logs (line 432)
    }

    # Call generate_reports
    tracker.generate_reports([host])

    # Verify stats were tracked despite many logs
    assert tracker.remote_opens["test-host"] == 15
