[tox]
envlist =
    py38, py39, py310, py311, py312, py313, py314, pre-commit
skip_missing_interpreters = true

[testenv]
runner = uv-venv-lock-runner
dependency_groups = test
setenv =
    APPENV_BEST_PYTHON = {envpython}
    COLUMNS = 80
    IN_TOX_TEST = 1
commands = pytest {posargs}

[testenv:pre-commit]
runner = uv-venv-lock-runner
dependency_groups = pre-commit
description = This env runs all linters configured in .pre-commit-config.yaml
skip_install = true
commands =
    pre-commit run --all-files --show-diff-on-failure
