from typing import Any, Protocol

class OutputBackend(Protocol):
    def line(self, message: str, **fmt: Any) -> None: ...
    def sep(self, sep: str, title: str, **fmt: Any) -> None: ...
    def write(self, content: str, **fmt: Any) -> None: ...

class TerminalBackend:
    _tw: Any

    def __init__(self) -> None: ...
    def line(self, message: str, **fmt: Any) -> None: ...
    def sep(self, sep: str, title: str, **fmt: Any) -> None: ...
    def write(self, content: str, **fmt: Any) -> None: ...

class NullBackend:
    def line(self, message: str, **fmt: Any) -> None: ...
    def sep(self, sep: str, title: str, **fmt: Any) -> None: ...
    def write(self, content: str, **fmt: Any) -> None: ...

class TestBackend:
    output: str

    def __init__(self) -> None: ...
    def line(self, message: str, **fmt: Any) -> None: ...
    def sep(self, sep: str, title: str, **fmt: Any) -> None: ...
    def write(self, content: str, **fmt: Any) -> None: ...

# The output module imports Output from remote_core
# Import at end to avoid circular import issues
from batou.remote_core import Output  # noqa: E402

output: Output
