from typing import Any

class TerminalBackend:
    _tw: Any

    def __init__(self): ...
    def line(self, message: str, **format): ...
    def sep(self, sep: str, title: str, **format): ...
    def write(self, content: str, **format): ...

class NullBackend:
    def line(self, message: str, **format): ...
    def sep(self, sep: str, title: str, **format): ...
    def write(self, content: str, **format): ...

class TestBackend:
    output: str

    def __init__(self): ...
    def line(self, message: str, **format): ...
    def sep(self, sep: str, title: str, **format): ...
    def write(self, content: str, **format): ...

# The output module imports Output from remote_core
from batou.remote_core import Output

output: Output
enable_debug: bool
