class TerminalBackend:
    def __init__(self): ...
    def line(self, message: str, **format): ...
    def sep(self, sep: str, title: str, **format): ...


class TestBackend:
    def __init__(self): ...
    def line(self, message: str, **format): ...
    def sep(self, sep: str, title: str, **format): ...
