from typing import Any

from execnet.gateway_bootstrap import HostNotFound

from batou.environment import Environment

def check(
    environment: str, platform: str | None = ..., timeout: str | None = ...
) -> None: ...
def main(environment: str, platform: str | None, timeout: str | None): ...

class CheckCommand:
    environment_name: str
    platform: str | None
    timeout: str | None
    environment: Environment
    errors: list[Any]

    def __init__(self, environment: str, platform: str | None, timeout: str | None): ...
    def execute(self) -> int: ...
    def load_environment(self) -> None: ...
    def load_secrets(self) -> None: ...
    def report_results(self) -> None: ...
    def validate_configuration(self) -> list[HostNotFound | Any]: ...

class LocalValidator:
    def __init__(self, environment: Environment): ...
    def validate_configuration(self) -> list[HostNotFound | Any]: ...
