from batou.environment import Environment
from execnet.gateway_bootstrap import HostNotFound
from typing import (
    Any,
    List,
    Union,
)

def main(environment: str, platform: None, timeout: None): ...

class CheckCommand:
    def __init__(self, environment: str, platform: None, timeout: None): ...
    def execute(self) -> int: ...
    def load_environment(self): ...
    def load_secrets(self): ...
    def report_results(self): ...
    def validate_configuration(self): ...

class LocalValidator:
    def __init__(self, environment: Environment): ...
    def validate_configuration(self) -> list[HostNotFound | Any]: ...
