from batou.environment import Environment
from batou.host import (
    Host,
    LocalHost,
    RemoteHost,
)
from batou.lib.cron import (
    CronTab,
    DebianInstallCrontab,
    FCInstallCrontab,
)
from batou.lib.debian import (
    LogrotateCronjob,
    RebootCronjob,
    Supervisor,
)
from batou.lib.file import (
    File,
    Mode,
    Presence,
)
from batou.lib.logrotate import GoceptNetRotatedLogrotate
from batou.lib.service import Service
from batou.lib.supervisor import Supervisor
from batou.utils import Address
from mock.mock import Mock
from pathlib._local import PosixPath
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Tuple,
    Type,
    Union,
)


class Attribute:
    def __get__(
        self,
        obj: Optional[Union[Supervisor, CronTab, Mode, Supervisor]],
        objtype: Optional[Union[Type[Supervisor], Type[Supervisor], Type[CronTab], Type[Mode]]] = ...
    ) -> Any: ...
    def __init__(
        self,
        conversion: Union[Type[int], str, Type[Address], Type[str]] = ...,
        default: Any = ...,
        expand: bool = ...,
        map: bool = ...
    ): ...
    def __set__(
        self,
        obj: Union[Supervisor, CronTab, Mode, Supervisor],
        value: Any
    ): ...
    def __set_name__(
        self,
        owner: Union[Type[Supervisor], Type[Supervisor], Type[CronTab], Type[Mode]],
        name: str
    ): ...
    def convert_list(self, value: str) -> List[Union[Any, str]]: ...
    def convert_literal(self, value: str) -> Union[bool, List[int]]: ...
    def from_config_string(
        self,
        obj: Union[Supervisor, CronTab, Supervisor],
        value: ConfigString
    ) -> Union[Address, str]: ...


class Component:
    def __add__(self, component: Any) -> Component: ...
    def __enter__(self): ...
    def __exit__(self, type: None, value: None, tb: None): ...
    def __init__(self, namevar: Optional[Union[Service, str, PosixPath]] = ..., **kw): ...
    def __or__(self, component: Component) -> Component: ...
    def __repr__(self) -> str: ...
    def __setup_event_handlers__(self): ...
    def __trigger_event__(self, event: str, predict_only: bool): ...
    @classmethod
    def _add_platform(
        cls,
        name: str,
        platform: Union[Type[DebianInstallCrontab], Type[RebootCronjob], Type[LogrotateCronjob], Type[GoceptNetRotatedLogrotate], Type[FCInstallCrontab]]
    ): ...
    @property
    def _breadcrumb(self) -> str: ...
    @property
    def _breadcrumbs(self) -> str: ...
    def _get_platform(self) -> None: ...
    def _overrides(self, overrides: Dict[Any, Any] = ...): ...
    def _template_args(self, component: Optional[Any] = ..., **kw) -> Dict[str, Any]: ...
    def assert_cmd(self, *args, **kw): ...
    def assert_component_is_current(
        self,
        requirements: Union[Component, List[Union[Presence, File]], List[Component], List[Presence]] = ...,
        **kw
    ): ...
    def assert_file_is_current(self, reference: str, requirements: List[Union[Any, str]] = ..., **kw): ...
    def assert_no_changes(self): ...
    def assert_no_subcomponent_changes(self): ...
    def chdir(self, path: str): ...
    def checksum(self, value: Optional[bytes] = ...) -> str: ...
    def cmd(
        self,
        cmd: str,
        silent: bool = ...,
        ignore_returncode: bool = ...,
        communicate: bool = ...,
        env: None = ...,
        expand: bool = ...
    ) -> Tuple[str, str]: ...
    def configure(self): ...
    @property
    def defdir(self) -> str: ...
    def deploy(self, predict_only: bool = ...): ...
    @property
    def environment(self) -> Union[Environment, Mock]: ...
    def expand(self, string: Union[ConfigString, str], component: Optional[Any] = ..., **kw) -> str: ...
    @property
    def host(self) -> Union[LocalHost, Host, RemoteHost, Mock]: ...
    def last_updated(self): ...
    def map(self, path: Union[PosixPath, str]) -> str: ...
    @property
    def namevar_for_breadcrumb(self) -> Union[Service, str]: ...
    def prepare(self, parent: Any): ...
    def provide(self, key: str, value: Any): ...
    @property
    def recursive_sub_components(self): ...
    def require(
        self,
        key: str,
        host: Optional[Host] = ...,
        strict: bool = ...,
        reverse: bool = ...,
        dirty: bool = ...
    ) -> List[Any]: ...
    def require_one(
        self,
        key: str,
        host: Optional[Host] = ...,
        strict: bool = ...,
        reverse: bool = ...,
        dirty: bool = ...
    ) -> Union[Supervisor, int]: ...
    @property
    def root(self) -> Union[RootComponent, Mock]: ...
