from typing import Any

from pydantic import BaseModel

def _value_to_legacy_string(value: Any) -> str: ...
def _find_line_for_key(content: str, location: str) -> int | None: ...
def _find_resolver_host_line(content: str, hostname: str) -> int | None: ...
def _collect_validation_errors(e: Any, content: str) -> list[dict[str, Any]]: ...
def _format_validation_errors_from_list(errors: list[dict[str, Any]]) -> str: ...
def _format_validation_errors(e: Any, content: str = "") -> str: ...
def load_toml_config(content: str, source: str = ...) -> EnvironmentConfig: ...
def to_legacy_format(config: EnvironmentConfig) -> dict[str, dict[str, str]]: ...

class EnvironmentSettings(BaseModel):
    # Field annotations intentionally omitted - runtime validation via Pydantic
    @classmethod
    def validate_timeout(cls, v: int) -> int: ...

class HostConfig(BaseModel):
    # Field annotations intentionally omitted - runtime validation via Pydantic
    def get_data_attributes(self) -> dict[str, str]: ...

class EnvironmentConfig(BaseModel):
    # Field annotations intentionally omitted - runtime validation via Pydantic
    @classmethod
    def validate_resolver_ips(
        cls, v: dict[str, str | list[str]],
    ) -> dict[str, str | list[str]]: ...
    @staticmethod
    def _is_valid_ip(ip: str) -> bool: ...
    def get_all_hosts(self) -> dict[str, HostConfig]: ...

class ConfigLoadError(Exception):
    message: str
    details: str | None
    errors: list[dict]
    source_file: str | None

    def __init__(
        self,
        message: str,
        details: str | None = ...,
        errors: list[dict] | None = ...,
        source_file: str | None = ...,
    ) -> None: ...

class DictConfigSection(dict):
    def as_list(self, option: str) -> list[str]: ...

class DictConfig:
    def __init__(self, data: dict[str, dict[str, str]]) -> None: ...
    def __contains__(self, section: str) -> bool: ...
    def __getitem__(self, section: str) -> DictConfigSection: ...
    def __iter__(self) -> Any: ...
    def get(
        self, section: str, default: dict[str, str] | None = ...,
    ) -> DictConfigSection | dict[str, str]: ...
    def options(self, section: str) -> list[str]: ...
