from batou.component import RootComponent
from batou.host import (
    Host,
    LocalHost,
    RemoteHost,
)
from mock.mock import Mock
from pathlib._local import PosixPath
from typing import (
    Any,
    DefaultDict,
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    Union,
)


def parse_host_components(components: List[str]) -> Dict[str, Union[Dict[str, Union[List[str], bool]], Dict[str, bool]]]: ...


class Config:
    def __contains__(self, section: str) -> bool: ...
    def __getitem__(self, section: str) -> ConfigSection: ...
    def __init__(self, path: Optional[PosixPath]): ...
    def get(self, section: str, default: Optional[Dict[Any, Any]] = ...) -> ConfigSection: ...


class ConfigSection:
    def as_list(self, option: str) -> List[str]: ...


class Environment:
    def __init__(
        self,
        name: Union[Environment, str],
        timeout: Optional[int] = ...,
        platform: Optional[str] = ...,
        basedir: str = ...,
        provision_rebuild: bool = ...,
        check_and_predict_local: bool = ...
    ): ...
    def _environment_path(self, path: str = ...) -> str: ...
    def _host_data(self) -> Dict[str, Dict[Any, Any]]: ...
    def _load_host_components(
        self,
        host: Union[RemoteHost, Host, LocalHost],
        component_list: List[str]
    ): ...
    def _load_hosts_multi_section(self, config: Config): ...
    def _load_hosts_single_section(self, config: Config): ...
    def _set_defaults(self): ...
    def add_root(
        self,
        component_name: str,
        host: Union[LocalHost, Host, RemoteHost],
        features: Union[List[str], Tuple[()]] = ...,
        ignore: bool = ...
    ) -> RootComponent: ...
    @classmethod
    def all(cls): ...
    def components_for(self, host: LocalHost) -> Dict[str, RootComponent]: ...
    def configure(self) -> List[Any]: ...
    @classmethod
    def filter(cls, filter: str) -> List[Environment]: ...
    def get_host(self, hostname: str) -> Mock: ...
    def get_root(
        self,
        component_name: str,
        host: Union[Host, RemoteHost]
    ) -> RootComponent: ...
    def load(self): ...
    def load_environment(self, config: Config): ...
    def load_hosts(self, config: Config): ...
    def load_provisioners(self, config: Config): ...
    def load_resolver(self, config: Config): ...
    def load_secrets(self): ...
    def map(self, path: str) -> str: ...
    def prepare_connect(self): ...
    def root_dependencies(
        self,
        host: Optional[str] = ...
    ) -> Union[DefaultDict[RootComponent, Union[Set[RootComponent], Set[Any]]], DefaultDict[RootComponent, Set[Any]], DefaultDict[RootComponent, Set[RootComponent]]]: ...


class UnknownEnvironmentError:
    def __init__(self, names: list): ...
    def __str__(self) -> str: ...
