class FCDevVM:
    def __init__(self, name: str): ...
    @classmethod
    def from_config_section(cls, name: str, section: dict[str, str]) -> FCDevVM: ...

from typing import Any, Self

class Provisioner:
    name: str
    rebuild: bool

    def __init__(self, name: str): ...
    @classmethod
    def from_config_section(cls, name: str, section: dict[str, str]) -> Self: ...
    def provision(self, host: Any) -> None: ...
    def suggest_name(self, name: str) -> str: ...
