from batou._output import NullBackend
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Tuple,
    Union,
)


def _hg_current_id() -> str: ...


def build_batou(): ...


def cmd(c: str, acceptable_returncodes: list[int] = ...) -> tuple[bytes, bytes]: ...


def deploy(root: str, predict_only: bool = ...): ...


def ensure_base(base: str) -> str: ...


def ensure_repository(target: str, method: str) -> str: ...


def git_pull_code(upstream: str, branch: str): ...


def git_unbundle_code(): ...


def git_update_working_copy(branch: str) -> str: ...


def hg_current_heads() -> list[str]: ...


def hg_pull_code(upstream: str): ...


def hg_unbundle_code(): ...


def hg_update_working_copy(branch: str) -> str: ...


def lock(): ...


def whoami() -> str: ...


class Deployment:
    def __init__(
        self,
        env_name: str,
        host_name: str,
        overrides: dict[Any, Any],
        resolve_override: dict[str, str],
        resolve_v6_override: dict[str, str],
        secret_files: None,
        secret_data: None,
        host_data: dict[Any, Any],
        timeout: None,
        platform: None,
        debug_settings_dict: dict[Any, Any],
        os_env: dict[str, str] | None = ...
    ): ...
    def load(self) -> list[Any]: ...


class Output:
    def __init__(self, backend: NullBackend): ...
    def annotate(self, message: str, debug: bool = ..., icon: bool | str = ..., **format): ...
    def buffer(self, cmd: str, *args, **kw): ...
    def clear_buffer(self): ...
    def error(self, message: str, exc_info: None = ..., debug: bool = ...): ...
    def flush_buffer(self): ...
    def line(self, message: str, debug: bool = ..., icon: bool | str | None = ..., **format): ...
    def section(self, title: str, debug: bool = ..., **format): ...
    def sep(self, sep: str, title: str, **format) -> None: ...
    def step(self, context: str, message: str, debug: bool = ..., icon: bool | str | None = ..., **format): ...
    def tabular(self, key: str, value: str, separator: str = ..., debug: bool = ..., **kw): ...
    def warn(self, message: str, debug: bool = ...): ...
