from typing import Any

from batou.environment import Environment
from batou.host import RemoteHost

def cmd(c: str, *args: Any, **kw: Any) -> tuple[str, str]: ...
def find_line_with(prefix: str, output: str) -> str | None: ...
def hg_cmd(hgcmd: str) -> list[dict[str, Any]]: ...

class Repository:
    environment: Environment
    root: str

    def __init__(self, environment: Environment) -> None: ...
    @classmethod
    def from_environment(
        cls,
        environment: Environment,
    ) -> (
        RSyncRepository
        | RSyncDevRepository
        | RSyncExtRepository
        | NullRepository
        | MercurialRepository
        | GitRepository
    ): ...
    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class NullRepository(Repository): ...

class FilteredRSync:
    IGNORE_LIST: tuple[str, ...]

    def __init__(self, *args: Any, **kw: Any) -> None: ...
    def add_target(self, gateway: Any, target: str) -> None: ...
    def filter(self, path: str) -> bool: ...
    def send(self) -> None: ...

class RSyncRepository(Repository):
    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class RSyncExtRepository(Repository):
    IGNORE_LIST: tuple[str, ...]
    SYNC_OPTS: list[str]

    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class RSyncDevRepository(RSyncExtRepository):
    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class MercurialRepository(Repository):
    root: str | None
    branch: str
    subdir: str

    def __init__(self, environment: Environment) -> None: ...
    @property
    def upstream(self) -> str: ...
    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class MercurialPullRepository(MercurialRepository):
    def _ship(self, host: RemoteHost) -> None: ...

class MercurialBundleRepository(MercurialRepository):
    def _ship(self, host: RemoteHost) -> None: ...

class GitRepository(Repository):
    root: str | None
    branch: str
    subdir: str
    remote: str

    def __init__(self, environment: Environment) -> None: ...
    @property
    def upstream(self) -> str: ...
    def update(self, host: RemoteHost) -> None: ...
    def verify(self) -> None: ...

class GitPullRepository(GitRepository):
    def _ship(self, host: RemoteHost) -> None: ...

class GitBundleRepository(GitRepository):
    def _ship(self, host: RemoteHost) -> None: ...
