from batou.environment import Environment
from batou.host import RemoteHost
from typing import (
    Any,
    Dict,
    List,
    Optional,
    Tuple,
    Union,
)

def cmd(c: str, *args, **kw) -> Tuple[str, str]: ...
def find_line_with(prefix: str, output: str) -> Optional[str]: ...
def hg_cmd(hgcmd: str) -> List[Dict[str, Any]]: ...

class Repository:
    environment: Environment
    root: str

    def __init__(self, environment: Environment): ...
    @classmethod
    def from_environment(
        cls, environment: Environment
    ) -> Union[
        "RSyncRepository",
        "RSyncDevRepository",
        "RSyncExtRepository",
        "NullRepository",
        "MercurialRepository",
        "GitRepository",
    ]: ...
    def update(self, host: RemoteHost): ...
    def verify(self): ...

class NullRepository(Repository):
    pass

class FilteredRSync:
    IGNORE_LIST: Tuple[str, ...]

    def __init__(self, *args, **kw): ...
    def add_target(self, gateway: Any, target: str): ...
    def filter(self, path: str) -> bool: ...
    def send(self): ...

class RSyncRepository(Repository):
    def update(self, host: RemoteHost): ...
    def verify(self): ...

class RSyncExtRepository(Repository):
    IGNORE_LIST: Tuple[str, ...]
    SYNC_OPTS: List[str]

    def update(self, host: RemoteHost): ...
    def verify(self): ...

class RSyncDevRepository(RSyncExtRepository):
    def update(self, host: RemoteHost): ...
    def verify(self): ...

class MercurialRepository(Repository):
    root: Optional[str]
    branch: str
    subdir: str

    def __init__(self, environment: Environment): ...
    @property
    def upstream(self) -> str: ...
    def update(self, host: RemoteHost): ...
    def verify(self): ...

class MercurialPullRepository(MercurialRepository):
    def _ship(self, host: RemoteHost): ...

class MercurialBundleRepository(MercurialRepository):
    def _ship(self, host: RemoteHost): ...

class GitRepository(Repository):
    root: Optional[str]
    branch: str
    subdir: str
    remote: str

    def __init__(self, environment: Environment): ...
    @property
    def upstream(self) -> str: ...
    def update(self, host: RemoteHost): ...
    def verify(self): ...

class GitPullRepository(GitRepository):
    def _ship(self, host: RemoteHost): ...

class GitBundleRepository(GitRepository):
    def _ship(self, host: RemoteHost): ...
