from io import StringIO
from typing import (
    Any,
)

from jinja2.environment import Template

class Jinja2Engine:
    env: Any
    cache_enabled: bool
    _instance: Jinja2Engine | None
    _max_cache_size: int
    _enable_cache: bool

    def __init__(self, *args, **kwargs): ...
    @staticmethod
    def __new__(cls: type[Jinja2Engine], *args, **kwargs) -> Jinja2Engine: ...
    def _compile_template(self, templatestr: str) -> Template: ...
    def _evict_lru(self): ...
    def _render_template_file(
        self, sourcefile: str, args: dict[str, Any]
    ) -> StringIO: ...
    def _reset_cache_stats(self): ...
    def expand(
        self, templatestr: str, args: dict[str, Any], identifier: str = ...
    ) -> str: ...
    def reset_cache(self): ...
    def retrieve_cache_stats(self) -> dict[str, int]: ...

class TemplateEngine:
    @classmethod
    def get(cls, enginename: str) -> Jinja2Engine: ...
    def _render_template_file(self, sourcefile: str, args: dict[str, Any]): ...
    def expand(self, templatestr: str, args: dict[str, Any]): ...
    def template(self, sourcefile: str, args: dict[str, Any]) -> str: ...
