import subprocess
import types
from collections import defaultdict
from collections.abc import Callable
from contextlib import AbstractContextManager
from typing import Any, Literal

# Type alias for graph structures
type Graph = defaultdict[Any, set[Any]]

# Module variables
notify: Callable[[str, str], None]
resolve_override: dict[str, str]
resolve_v6_override: dict[str, str]
ADDR_DEFAULT: object

def call_with_optional_args(func: Callable, **kw: Any) -> Any: ...
def cmd(
    cmd: str | list[str],
    silent: bool = ...,
    ignore_returncode: bool = ...,
    communicate: bool = ...,
    env: dict[str, str] | None = ...,
    acceptable_returncodes: list[int] = ...,
    encoding: str | None = ...,
) -> tuple[str, str] | subprocess.Popen: ...
def dict_merge(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]: ...
def ensure_graph_data(graph: Graph) -> Graph: ...
def escape_macosx_string(s: str) -> str: ...
def export_environment_variables(env: dict[str, str]) -> str: ...
def find_basedir() -> str: ...
def flatten(list_of_lists: list[list[Any]]) -> list[Any]: ...
def format_duration(duration: float | None) -> str: ...
def get_output(command: str, default: str | None = ...) -> str: ...
def hash_file(path: str, function: str = ...) -> str: ...
def locked(
    filename: str,
    exit_on_failure: bool = ...,
) -> AbstractContextManager[None]: ...
def notify_macosx(title: str, description: str) -> None: ...
def notify_none(title: str, description: str) -> None: ...
def notify_send(title: str, description: str) -> None: ...
def remove_nodes_without_outgoing_edges(graph: Graph) -> None: ...
def resolve(
    host: str,
    port: int = ...,
    resolve_override: dict[str, str] = ...,
) -> str: ...
def resolve_v6(
    host: str,
    port: int = ...,
    resolve_override: dict[str, str] = ...,
) -> str: ...
def revert_graph(graph: Graph) -> Graph: ...
def self_id() -> str: ...
def topological_sort(graph: Graph) -> list[Any]: ...

class Address:
    connect: NetLoc
    require_v4: Literal[True, False, "optional"]
    require_v6: Literal[True, False, "optional"]

    def __init__(
        self,
        connect_address: str,
        port: int | str | None = ...,
        require_v4: Literal[True, False, "optional"] = ...,
        require_v6: Literal[True, False, "optional"] = ...,
    ) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @property
    def listen(self) -> NetLoc | None: ...
    @listen.setter
    def listen(self, value: NetLoc | None) -> None: ...
    @property
    def listen_v6(self) -> NetLoc | None: ...
    @listen_v6.setter
    def listen_v6(self, value: NetLoc | None) -> None: ...

class BagOfAttributes(dict):
    def __getattr__(self, key: str) -> Any: ...

class CmdExecutionError(Exception):
    cmd: str
    returncode: int
    stdout: str
    stderr: str

    def __init__(
        self,
        cmd: str,
        returncode: int,
        stdout: str,
        stderr: str,
    ) -> None: ...
    def report(self) -> str: ...

class CycleError(ValueError): ...

class MultiFile:
    files: list[Any]

    def __init__(self, files: list[Any]) -> None: ...
    def flush(self) -> None: ...
    def write(self, value: str) -> None: ...

class NetLoc:
    host: str
    port: int | str | None

    def __init__(self, host: str, port: int | str | None = ...) -> None: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...

class Timer:
    durations: dict[str, float]
    tag: str | None

    def __init__(self, tag: str | None = ...) -> None: ...
    def above_threshold(self, **thresholds: float) -> tuple[bool, list[str]]: ...
    def humanize(self, *steps: str) -> str: ...
    def step(self, note: str) -> Timer.TimerContext: ...

    class TimerContext:
        timer: Timer
        note: str
        start: float

        def __enter__(self) -> None: ...
        def __exit__(
            self,
            exc_type: type[BaseException] | None,
            exc_value: BaseException | None,
            traceback: types.TracebackType | None,
        ) -> None: ...
        def __init__(self, timer: Timer, note: str) -> None: ...
