from typing import (
    Any,
    Callable,
    DefaultDict,
    Dict,
    Generator,
    Iterator,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
)

# Type alias for graph structures
Graph = DefaultDict[Any, Set[Any]]

def call_with_optional_args(func: Callable, **kw) -> Any: ...
def cmd(
    cmd: Union[str, List[str]],
    silent: bool = ...,
    ignore_returncode: bool = ...,
    communicate: bool = ...,
    env: Optional[Dict[str, str]] = ...,
    acceptable_returncodes: List[int] = ...,
    encoding: Optional[str] = ...,
) -> Union[Tuple[bytes, bytes], Tuple[str, str], Any]: ...
def dict_merge(a: Dict[str, Any], b: Dict[str, Any]) -> Dict[str, Any]: ...
def ensure_graph_data(graph: Graph) -> Graph: ...
def escape_macosx_string(s: str) -> str: ...
def flatten(list_of_lists: List[List[Any]]) -> List[Any]: ...
def format_duration(duration: Optional[float]) -> str: ...
def hash(path: str, function: str = ...) -> str: ...
def locked(filename: str, exit_on_failure: bool = ...): ...
def notify_macosx(title: str, description: str): ...
def remove_nodes_without_outgoing_edges(graph: Graph): ...
def resolve(
    host: str, port: int = ..., resolve_override: Dict[str, str] = ...
) -> str: ...
def resolve_v6(
    host: str, port: int = ..., resolve_override: Dict[str, str] = ...
) -> str: ...
def revert_graph(graph: Graph) -> Graph: ...
def self_id() -> str: ...
def topological_sort(graph: Graph) -> List[Any]: ...

class Address:
    connect: "NetLoc"
    require_v4: Union[bool, str]
    require_v6: Union[bool, str]

    def __init__(
        self,
        connect_address: str,
        port: Optional[Union[int, str]] = ...,
        require_v4: Union[bool, str, object] = ...,
        require_v6: Union[bool, str, object] = ...,
    ): ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    @property
    def listen(self) -> Optional["NetLoc"]: ...
    @listen.setter
    def listen(self, value: Optional["NetLoc"]): ...
    @property
    def listen_v6(self) -> Optional["NetLoc"]: ...
    @listen_v6.setter
    def listen_v6(self, value: Optional["NetLoc"]): ...

class BagOfAttributes(dict):
    def __getattr__(self, key: str) -> Any: ...

class CmdExecutionError(Exception):
    cmd: str
    returncode: int
    stdout: str
    stderr: str

    def __init__(self, cmd: str, returncode: int, stdout: str, stderr: str): ...
    def __str__(self) -> str: ...
    def report(self): ...

class CycleError(ValueError):
    def __str__(self) -> str: ...

class MultiFile:
    files: List[Any]

    def __init__(self, files: List[Any]): ...
    def flush(self): ...
    def write(self, value: str): ...

class NetLoc:
    host: str
    port: Optional[Union[int, str]]

    def __init__(self, host: str, port: Optional[Union[int, str]] = ...): ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Timer:
    durations: Dict[str, float]
    tag: Optional[str]

    def __init__(self, tag: Optional[str] = ...): ...
    def above_threshold(self, **thresholds) -> Tuple[bool, List[str]]: ...
    def humanize(self, *steps) -> str: ...
    def step(self, note: str) -> "Timer.TimerContext": ...

    class TimerContext:
        timer: Timer
        note: str
        start: float

        def __enter__(self) -> None: ...
        def __exit__(
            self,
            exc_type: Optional[Type[BaseException]],
            exc_value: Optional[BaseException],
            traceback: Optional[Any],
        ) -> None: ...
        def __init__(self, timer: Timer, note: str): ...
