from typing import (
    Any,
    DefaultDict,
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    Type,
    Union,
)
from collections.abc import Callable, Generator, Iterator

# Type alias for graph structures
Graph = DefaultDict[Any, set[Any]]

def call_with_optional_args(func: Callable, **kw) -> Any: ...
def cmd(
    cmd: str | list[str],
    silent: bool = ...,
    ignore_returncode: bool = ...,
    communicate: bool = ...,
    env: dict[str, str] | None = ...,
    acceptable_returncodes: list[int] = ...,
    encoding: str | None = ...,
) -> tuple[bytes, bytes] | tuple[str, str] | Any: ...
def dict_merge(a: dict[str, Any], b: dict[str, Any]) -> dict[str, Any]: ...
def ensure_graph_data(graph: Graph) -> Graph: ...
def escape_macosx_string(s: str) -> str: ...
def flatten(list_of_lists: list[list[Any]]) -> list[Any]: ...
def format_duration(duration: float | None) -> str: ...
def hash(path: str, function: str = ...) -> str: ...
def locked(filename: str, exit_on_failure: bool = ...): ...
def notify_macosx(title: str, description: str): ...
def remove_nodes_without_outgoing_edges(graph: Graph): ...
def resolve(
    host: str, port: int = ..., resolve_override: dict[str, str] = ...
) -> str: ...
def resolve_v6(
    host: str, port: int = ..., resolve_override: dict[str, str] = ...
) -> str: ...
def revert_graph(graph: Graph) -> Graph: ...
def self_id() -> str: ...
def topological_sort(graph: Graph) -> list[Any]: ...

class Address:
    connect: NetLoc
    require_v4: bool | str
    require_v6: bool | str

    def __init__(
        self,
        connect_address: str,
        port: int | str | None = ...,
        require_v4: bool | str | object = ...,
        require_v6: bool | str | object = ...,
    ): ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __str__(self) -> str: ...
    @property
    def listen(self) -> Optional[NetLoc]: ...
    @listen.setter
    def listen(self, value: Optional[NetLoc]): ...
    @property
    def listen_v6(self) -> Optional[NetLoc]: ...
    @listen_v6.setter
    def listen_v6(self, value: Optional[NetLoc]): ...

class BagOfAttributes(dict):
    def __getattr__(self, key: str) -> Any: ...

class CmdExecutionError(Exception):
    cmd: str
    returncode: int
    stdout: str
    stderr: str

    def __init__(self, cmd: str, returncode: int, stdout: str, stderr: str): ...
    def __str__(self) -> str: ...
    def report(self): ...

class CycleError(ValueError):
    def __str__(self) -> str: ...

class MultiFile:
    files: list[Any]

    def __init__(self, files: list[Any]): ...
    def flush(self): ...
    def write(self, value: str): ...

class NetLoc:
    host: str
    port: int | str | None

    def __init__(self, host: str, port: int | str | None = ...): ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...

class Timer:
    durations: dict[str, float]
    tag: str | None

    def __init__(self, tag: str | None = ...): ...
    def above_threshold(self, **thresholds) -> tuple[bool, list[str]]: ...
    def humanize(self, *steps) -> str: ...
    def step(self, note: str) -> Timer.TimerContext: ...

    class TimerContext:
        timer: Timer
        note: str
        start: float

        def __enter__(self) -> None: ...
        def __exit__(
            self,
            exc_type: type[BaseException] | None,
            exc_value: BaseException | None,
            traceback: Any | None,
        ) -> None: ...
        def __init__(self, timer: Timer, note: str): ...
