from batou.environment import ConfigSection, Environment

class Map:
    def __init__(self, environment: Environment, config: ConfigSection | None): ...
    def map(self, path: str) -> str: ...

class Developer:
    def __init__(self, environment: Environment, config: ConfigSection | None): ...
    def map(self, path: str) -> str: ...
