from batou.secrets.encryption import (
    AGEEncryptedFile,
    DiffableAGEEncryptedFile,
    EncryptedFile,
    GPGEncryptedFile,
)
from configupdater.configupdater import ConfigUpdater
from pathlib._local import PosixPath
from typing import (
    Dict,
    List,
    Optional,
    Set,
    Tuple,
    Union,
)


def process_age_recipients(members: List[str], environment_path: PosixPath) -> Tuple[List[str], bool]: ...


class AGESecretProvider:
    def __init__(self, environment: Environment): ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> List[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> Dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...): ...


class ConfigFileSecretProvider:
    def _get_recipients(self) -> List[str]: ...
    @property
    def config(self) -> ConfigUpdater: ...
    def edit(
        self,
        edit_file: Optional[str] = ...
    ) -> Union[GPGEncryptedFile, AGEEncryptedFile, DiffableAGEEncryptedFile]: ...
    def read(self) -> SecretBlob: ...
    def read_secret_files(self) -> Dict[str, bytes]: ...
    def summary(self): ...
    def write_file(self, file: EncryptedFile, content: bytes): ...
    def write_secret_files(self, secret_files: Dict[str, bytes]): ...


class DiffableAGESecretProvider:
    def __init__(self, environment: Environment): ...


class GPGSecretProvider:
    def __init__(self, environment: Environment): ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> List[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> Dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...): ...


class NoSecretProvider:
    def __init__(self, environment: Environment): ...
    def read(self) -> SecretBlob: ...


class SecretBlob:
    def __init__(
        self,
        host_data: Dict[str, Dict[str, str]],
        component_overrides: Dict[str, Dict[str, str]],
        secret_data: Set[str],
        secret_files: Dict[str, str]
    ): ...


class SecretProvider:
    def __init__(self, environment: Environment): ...
    @classmethod
    def from_environment(cls, environment: Environment) -> SecretProvider: ...
    def inject_secrets(self): ...
