from pathlib import Path
from typing import Literal

from configupdater.configupdater import ConfigUpdater

from batou.environment import Environment
from batou.secrets.encryption import (
    AGEEncryptedFile,
    DiffableAGEEncryptedFile,
    EncryptedFile,
    GPGEncryptedFile,
)

def process_age_recipients(
    members: list[str],
    environment_path: Path,
) -> tuple[list[str], bool]: ...

class AGESecretProvider:
    def __init__(self, environment: Environment): ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> list[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...): ...

class ConfigFileSecretProvider:
    def _get_recipients(self) -> list[str]: ...
    @property
    def config(self) -> ConfigUpdater: ...
    def edit(
        self,
        edit_file: str | None = ...,
    ) -> GPGEncryptedFile | AGEEncryptedFile | DiffableAGEEncryptedFile: ...
    def read(self) -> SecretBlob: ...
    def read_secret_files(self) -> dict[str, bytes]: ...
    def summary(self): ...
    def write_file(self, file: EncryptedFile, content: bytes): ...
    def write_secret_files(self, secret_files: dict[str, bytes]): ...

class DiffableAGESecretProvider:
    def __init__(self, environment: Environment): ...

class GPGSecretProvider:
    def __init__(self, environment: Environment): ...
    def _get_file(self, name: str, writeable: bool = ...) -> EncryptedFile: ...
    def _get_recipients_for_encryption(self) -> list[str]: ...
    def iter_secret_files(self, writeable: bool = ...) -> dict[str, EncryptedFile]: ...
    def write_config(self, content: bytes, force_reencrypt: bool = ...): ...

class NoSecretProvider:
    def __init__(self, environment: Environment): ...
    def read(self) -> SecretBlob: ...

class SecretBlob:
    def __init__(
        self,
        host_data: dict[str, dict[str, str]],
        component_overrides: dict[str, dict[str, str]],
        secret_data: set[str],
        secret_files: dict[str, str],
    ): ...

class SecretProvider:
    secret_provider_str: Literal["gpg", "age", "age-diffable", "none"]
    def __init__(self, environment: Environment): ...
    @classmethod
    def from_environment(
        cls,
        environment: Environment,
    ) -> SecretProvider: ...  # extension: Literal[".gpg", ".age", ".age-diffable"]
    def inject_secrets(self): ...
