from batou.environment import Environment
from typing import Optional


class Editor:
    def __init__(self, editor_cmd: str, environment: Environment, edit_file: Optional[str] = ...): ...
    def edit(self): ...
    def interact(self): ...
    def process_cmd(self, cmd: str): ...
