
from batou.environment import Environment

class Editor:
    def __init__(
        self, editor_cmd: str, environment: Environment, edit_file: str | None = ...
    ): ...
    def edit(self): ...
    def interact(self): ...
    def process_cmd(self, cmd: str): ...
