import pathlib
import types

def expect(fd: int, expected: bytes) -> tuple[bool, bytes]: ...
def get_identities() -> list[str]: ...
def get_encrypted_file(path: pathlib.Path, writeable: bool = ...) -> EncryptedFile: ...

class AGEEncryptedFile:
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    @classmethod
    def age(cls) -> str: ...
    def decrypt(self) -> bytes: ...

class DiffableAGEEncryptedFile:
    def __init__(self, path: pathlib.Path, writeable: bool = ...) -> None: ...
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    def decrypt(self) -> bytes: ...
    def decrypt_age_string(self, content: str) -> str: ...
    def encrypt_age_string(self, content: str, recipients: list[str]) -> str: ...

class EncryptedFile:
    def __enter__(
        self,
    ) -> AGEEncryptedFile | DiffableAGEEncryptedFile | GPGEncryptedFile: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> bool | None: ...
    def __init__(self, path: pathlib.Path, writeable: bool = ...) -> None: ...
    def _lock(self) -> None: ...
    def _unlock(self) -> None: ...
    @property
    def cleartext(self) -> str: ...
    @property
    def decrypted(self) -> bytes: ...
    @property
    def locked(self) -> bool: ...
    def write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...

class GPGEncryptedFile:
    def _write(
        self,
        content: bytes,
        recipients: list[str],
        reencrypt: bool = ...,
    ) -> None: ...
    def decrypt(self) -> bytes: ...
    @classmethod
    def gpg(cls) -> str: ...
