from typing import (
    List,
    Tuple,
    Union,
)


def expect(fd: int, expected: bytes) -> Tuple[bool, bytes]: ...


def get_identities() -> List[str]: ...


class AGEEncryptedFile:
    def _write(self, content: bytes, recipients: List[str], reencrypt: bool = ...): ...
    @classmethod
    def age(cls) -> str: ...
    def decrypt(self) -> bytes: ...


class DiffableAGEEncryptedFile:
    def __init__(self, path: pathlib.Path, writeable: bool = ...): ...
    def _write(self, content: bytes, recipients: List[str], reencrypt: bool = ...): ...
    def decrypt(self) -> bytes: ...
    def decrypt_age_string(self, content: str) -> str: ...
    def encrypt_age_string(self, content: str, recipients: List[str]) -> str: ...


class EncryptedFile:
    def __enter__(
        self
    ) -> Union[AGEEncryptedFile, DiffableAGEEncryptedFile, GPGEncryptedFile]: ...
    def __exit__(self, exc_type: None, exc_value: None, traceback: None): ...
    def __init__(self, path: pathlib.Path, writeable: bool = ...): ...
    def _lock(self): ...
    def _unlock(self): ...
    @property
    def cleartext(self) -> str: ...
    @property
    def decrypted(self) -> bytes: ...
    @property
    def locked(self) -> bool: ...
    def write(self, content: bytes, recipients: List[str], reencrypt: bool = ...): ...


class GPGEncryptedFile:
    def _write(self, content: bytes, recipients: List[str], reencrypt: bool = ...): ...
    def decrypt(self) -> bytes: ...
    @classmethod
    def gpg(cls) -> str: ...
