from typing import Any

def add_user(keyid: str, environments: str, **kw: Any) -> None: ...
def reencrypt(environments: str, **kw: Any) -> None: ...
def remove_user(keyid: str, environments: str, **kw: Any) -> None: ...
def summary() -> int: ...
