
def assert_up_to_date() -> bool: ...
def get_current_version() -> int: ...
def get_expected_version() -> int: ...
def get_migration_steps() -> list[int]: ...
def main(*, bootstrap: bool = ...) -> None: ...
def migrate(base_version: int) -> int: ...
def output_migration_step(title: str, text: str, status: str = ...) -> None: ...
def read_config() -> int: ...
def write_config(version: int) -> None: ...
