name: Unit tests

on:
  push:
    branches: [main, 'batou-*']
  pull_request:
    branches: [main, 'batou-*']

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']

    runs-on: ubuntu-22.04

    steps:
      - name: Install age
        run: |
          sudo apt-get update
          sudo apt-get install -y age

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Show environment
        run: set

      - name: Test
        run: uvx --with tox-uv-bare tox -e py -- -vv
